# Generated by Django 4.1.5 on 2023-01-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True, verbose_name='бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_number', models.CharField(max_length=12, unique=True, verbose_name='Номер автомобиля')),
                ('motor_number', models.CharField(max_length=255, unique=True, verbose_name='Номер двигателя')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('registration_date', models.DateField(max_length=255, verbose_name='Дата регистрации')),
                ('is_stolen', models.BooleanField(verbose_name='Автомобиль угнан')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True, verbose_name='брэнд')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car', models.ManyToManyField(to='Cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.model'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.owner'),
        ),
        migrations.AddField(
            model_name='car',
            name='prev_ovner',
            field=models.ManyToManyField(blank=True, related_name='prev', to='Cars.owner'),
        ),
    ]
